Adjust preload script to allow --export arguments.

diff --git a/scripts/preload b/scripts/preload
--- a/scripts/preload
+++ b/scripts/preload
@@ -4,6 +4,7 @@ projfile=pyproject.toml
 libname=
 do_help=
 do_debug=
+exports=
 
 while [ $# -gt 0 ]; do
     if [ "$1" = "--help" ]; then
@@ -12,12 +13,23 @@ while [ $# -gt 0 ]; do
     elif [ "$1" = "--debug" ]; then
         do_debug=TRUE
         shift 1
-    elif [ $# -eq 1 ]; then
+    elif [ "$1" = "--export" ]; then
+        if [ $# -eq 1 ]; then
+            echo "Missing arg for --export"
+            exit 1
+        fi
+        exports="${exports}export $2; "
+        shift 2
+    elif [ -z "$libname" ]; then
        libname=$1
         shift 1
     else
-        echo "You can only preload one library at a time."
-        break
+       if [ "${1:0:1}" != "-" ]; then
+           echo "There can only be one <libname> argument."
+       else
+           echo "Unknown option: $1"
+       fi
+       exit 1
     fi
 done
 
@@ -63,12 +75,17 @@ elif [[ $version =~ "=" ]]; then
     exit 1
 fi
 
+if [ -n "${do_debug}" ]; then
+    echo "exports=$exports"
+fi
+
 maybe_simulate=""
 
 if [ -n "${do_debug}" ]; then
-   echo "SIMULATING..."
+   echo "SIMULATING... "
     maybe_simulate="echo "
 fi
 
-$maybe_simulate echo "Preloading ${libname} ${version}..."
-$maybe_simulate pip install "${libname}==${version}"
+${maybe_simulate}echo "Preloading ${libname} ${version}"
+${maybe_simulate}eval $exports
+${maybe_simulate}pip install "${libname}==${version}"
